apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources:
  - namespace.yaml
  - configmap-app-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
